name: Build Image UBI Builder

on:
  workflow_dispatch:
  schedule:
    - cron: "35 3 * * *" # WINTER (CST): 9:35PM  Summer (CDT): 10:35PM
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-image-ubi.yaml"
      - "ubi.containerfile"

env:
  TAG_PREFIX: runner-ubi
  UBI_VERSION: 9
  CONTAINERFILE: ubi.containerfile

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ env.CONTAINERFILE }}

  build:
    name: Build UBI Github Runner Image
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi9/ubi
      # Volume mount to workaround for https://github.com/redhat-actions/podman-login/issues/42 since the docker config from the host doesn't come up to the container
      options: --privileged -v /github/home/.docker/:/github/home/.docker/:rw
    needs: lint
    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get container tools in UBI builder
        run: dnf -y install podman buildah skopeo

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # https://github.com/redhat-actions/podman-login/issues/41
          auth_file_path: "/run/containers/0/auth.json"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          # Tags: runner-ubi runner-ubi-latest runner-ubi-${{ env.UBI_VERSION}} runner-ubi-YYMMDD frunner-ubi-SHA
          tags: |
            type=raw,value=${{ env.TAG_PREFIX}},enable={{is_default_branch}}
            type=raw,value=${{ env.TAG_PREFIX}}-latest,enable={{is_default_branch}}
            type=raw,value=${{ env.TAG_PREFIX}}-${{ env.UBI_VERSION}},enable={{is_default_branch}}
            type=schedule,prefix=${{ env.TAG_PREFIX}},pattern={{date 'YYYYMMDD' tz='America/Chicago'}},enable={{is_default_branch}}
            type=sha,prefix=${{ env.TAG_PREFIX}}-

      - name: Use buildah build to create the image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          build-args: |
            UBI_VERSION=${{ env.UBI_VERSION}}
          tags: ${{ steps.meta.outputs.tags }}
          containerfiles: ${{ env.CONTAINERFILE }}

      - name: Push to GitHub Container Repository
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
