name: Build all workspace images

on:
  workflow_dispatch:
  schedule:
    - cron: "35 4 * * 0" # WINTER (CST): 10:35PM  Summer (CDT): 11:35PM on SUNDAY
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-image.yaml"
      - "containerfile"

jobs:
  lint:
    name: General sanity check on environment
    runs-on: ubuntu-latest
    #runs-on: [self-hosted, linux]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: containerfile

  build:
    name: Build Image
    runs-on: ubuntu-latest
    #runs-on: [self-hosted, linux]
    container:
      image: ghcr.io/djarbz/ubi-podman:latest
      # Volume mount to workaround for https://github.com/redhat-actions/podman-login/issues/42 since the docker config from the host doesn't come up to the container
      options: --privileged -v /opt/:/host/opt/:rw -v /github/home/.docker/:/github/home/.docker/:rw
    needs: lint
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        flavor:
          - base
          - desktop
          - node
          - golang

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Replacing redhat-actions/podman-login
      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

        # Based on https://github.com/orgs/community/discussions/25678
      - name: Free up disk space on runner
        run: |
          rm -rf /host/opt/hostedtoolcache
          df -Th

      - name: Extract metadata (tags, labels) for Container Image
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ghcr.io/${{ github.repository }}
          # Tags: FLAVOR FLAVOR-latest FLAVOR-YYMMDD FLAVOR-SHA
          tags: |
            type=raw,value=${{ matrix.flavor }},enable={{is_default_branch}}
            type=raw,value=${{ matrix.flavor }}-latest,enable={{is_default_branch}}
            type=schedule,prefix=${{ matrix.flavor }},pattern={{date 'YYYYMMDD' tz='America/Chicago'}},enable={{is_default_branch}}
            type=sha,prefix=${{ matrix.flavor }}-

      # Replacing redhat-actions/buildah-build
      - name: Build Image with Buildah
        run: |
          # Convert tags from metadata-action into buildah arguments
          TAGS=(${{ steps.meta.outputs.tags }})
          FIRST_TAG=${TAGS[0]}

          buildah bud \
            --build-arg ENV_FLAVOR=${{ matrix.flavor }} \
            --file containerfile \
            --tag "$FIRST_TAG" .

          # Add extra tags to the local image
          for TAG in "${TAGS[@]:1}"; do
            buildah tag "$FIRST_TAG" "$TAG"
          done

      # Replacing redhat-actions/push-to-registry
      - name: Push to GHCR
        run: |
          for TAG in ${{ steps.meta.outputs.tags }}; do
            buildah push "$TAG"
          done
